version: "3.1"

services:
  library-card:
    build:
      context: .
    networks:
      - lan
    restart: unless-stopped
    environment:
      SQLITE3_DATABASE: /database/db.sqlite3
    volumes:
      - type: volume
        source: database
        target: /database

volumes:
  database:

networks:
  lan:
    attachable: true
